create table if not exists category
(
    id int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists manufacturer
(
    id int generated by default as identity primary key,
    name varchar(100) not null
);

create table if not exists item
(
    id int generated by default as identity primary key,
    serial_number varchar(50) not null,
    manufacturer_id bigint not null,
    category_id bigint not null,
    price decimal(12, 2) not null,
    quantity bigint not null,
    foreign key (manufacturer_id) references manufacturer(id) on delete cascade on update cascade,
    foreign key (category_id) references category(id) on delete cascade on update cascade
);

create table if not exists property
(
    id int generated by default as identity primary key,
    category_id bigint not null,
    name varchar(100) not null,
    foreign key (category_id) references category(id) on delete cascade on update cascade
);

create table if not exists item_property_value
(
    item_id bigint not null,
    property_id bigint not null,
    value varchar(100) not null,
    foreign key (item_id) references item(id) on delete cascade on update cascade,
    foreign key (property_id) references property(id) on delete cascade on update cascade,
    primary key (item_id, property_id)
);